### ISSUE TITLE
Error when connecting to helios.gov-cohesity.com

### ISSUE THREAD

**Issue by mpmiller1505** [cohesity/community-automation-samples#10]
To date, I have been unsuccessful in connecting to HeliosGov using the cohesity-api apiauth function.  When using -EntraID and specify my Helios SSO account, I am prompted for a ClientID.  The only "acceptable" response is to repeat my username, which then provides this error:

Error Connection: ERROR 12/02/2024 15:50:05                                                                             
{
  "error": "unsupported_response_type",
  "error_description": "AADSTS700052: The token request contains one or more unsupported response token type(s): \u0027BrowserIdToken,SessionToken,SignInStateToken\u0027. Trace ID: eece028b-d3a1-4dc8-abb9-e10876b27600 Correlation ID: c0fff465-4a39-421d-be32-4b8540bb570a Timestamp: 2024-12-02 20:50:05Z",
  "error_codes": [
    700052
  ],
  "timestamp": "2024-12-02 20:50:05Z",
  "trace_id": "eece028b-d3a1-4dc8-abb9-e10876b27600",
  "correlation_id": "c0fff465-4a39-421d-be32-4b8540bb570a"
}

**Comment by bseltz-cohesity** [comment]
Hi @mpmiller1505 
In order to authenticate for API access to Helios via SSO, you must register an SSO provider in Helios of type `OpenID Connect` (your existing SAML provider is not applicable to API access). Once you setup your OpenID Connect provider, it should be clear what your client ID is.

**Comment by mpmiller1505** [comment]
Ah, I see what you are referring to. We currently are setup with SAML. I'll investigate if we can support a switch to OpenID.
Thank you!

**Comment by bseltz-cohesity** [comment]
Don't switch, you need both. SAML provider supports login to the Helios UI. OpenID Connect supports API access.
